/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginFrame.java
 *
 * Created on Jan 3, 2012, 1:12:51 AM
 */

package valueMart;


import javax.swing.JOptionPane;




    /**
 *
 * @author FhAD khAn
 */
public final class LoginFrame extends javax.swing.JFrame  {

    /** Creates new form LoginFrame */
    public LoginFrame() {
        initComponents();
    }
    /*
    public void check(String type){
        if(type.equals("CEO")){
            
        }else if(type.equals("Branch Manager")){
            JOptionPane.showMessageDialog(this," Branch Manager Rights");
            
        }else if(type.equals("Sales Staff")){
           PlaceOrder.setEnabled(false);
            CancelOrder.setEnabled(false);
            OrderStatus.setEnabled(false);
            NewProduct.setEnabled(false);
            SearchProduct.setEnabled(false);
            updateProduct.setEnabled(false);
            newStock.setEnabled(false);
            searchStock.setEnabled(false);
            updateStock.setEnabled(false);
        }else if(type.equals("Purschase")){
            PlaceOrder.setEnabled(false);
            CancelOrder.setEnabled(false);
            OrderStatus.setEnabled(false);
            NewProduct.setEnabled(false);
            SearchProduct.setEnabled(false);
            updateProduct.setEnabled(false);
            newStock.setEnabled(false);
            searchStock.setEnabled(false);
            updateStock.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(this,"Stockist Rights");
            PlaceOrder.setEnabled(false);
            CancelOrder.setEnabled(false);
            OrderStatus.setEnabled(false);
            NewProduct.setEnabled(false);
            SearchProduct.setEnabled(false);
            updateProduct.setEnabled(false);
            newSupplier.setEnabled(false);
            updateSupplier.setEnabled(false);
            searchSupplier.setEnabled(false);                      
            
        } 
    
    }   
     */
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        PlaceOrder = new javax.swing.JButton();
        ManageOrder = new javax.swing.JLabel();
        CancelOrder = new javax.swing.JButton();
        OrderStatus = new javax.swing.JButton();
        NewProduct = new javax.swing.JButton();
        SearchProduct = new javax.swing.JButton();
        updateProduct = new javax.swing.JButton();
        ManageProduct = new javax.swing.JLabel();
        ManageSupplier = new javax.swing.JLabel();
        ManageInverntory = new javax.swing.JLabel();
        newSupplier = new javax.swing.JButton();
        updateSupplier = new javax.swing.JButton();
        searchSupplier = new javax.swing.JButton();
        newStock = new javax.swing.JButton();
        updateStock = new javax.swing.JButton();
        searchStock = new javax.swing.JButton();
        LoginName = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        AddProduct = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ManageOrder2 = new javax.swing.JLabel();
        ManageOrder3 = new javax.swing.JLabel();
        newSale = new javax.swing.JButton();
        searchSale = new javax.swing.JButton();
        AddPromotion = new javax.swing.JButton();
        veiwPromotion = new javax.swing.JButton();
        ManageOrder1 = new javax.swing.JLabel();
        ManageOrder4 = new javax.swing.JLabel();
        searchSale1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Value Mart");
        setResizable(false);

        PlaceOrder.setFont(new java.awt.Font("Forte", 1, 12));
        PlaceOrder.setText("Place Order");
        PlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceOrderActionPerformed(evt);
            }
        });

        ManageOrder.setFont(new java.awt.Font("Forte", 1, 12));
        ManageOrder.setText("Manage Order");

        CancelOrder.setFont(new java.awt.Font("Forte", 1, 12));
        CancelOrder.setText("Cancel Order");
        CancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelOrderActionPerformed(evt);
            }
        });

        OrderStatus.setFont(new java.awt.Font("Forte", 1, 12));
        OrderStatus.setText("Order Status");
        OrderStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderStatusActionPerformed(evt);
            }
        });

        NewProduct.setFont(new java.awt.Font("Forte", 1, 12));
        NewProduct.setText("NEw Product");
        NewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProductActionPerformed(evt);
            }
        });

        SearchProduct.setFont(new java.awt.Font("Forte", 1, 12));
        SearchProduct.setText("Search Product");
        SearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchProductActionPerformed(evt);
            }
        });

        updateProduct.setFont(new java.awt.Font("Forte", 1, 12));
        updateProduct.setText("Update product");
        updateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductActionPerformed(evt);
            }
        });

        ManageProduct.setFont(new java.awt.Font("Forte", 1, 12));
        ManageProduct.setText("Manage Product");

        ManageSupplier.setFont(new java.awt.Font("Forte", 1, 12));
        ManageSupplier.setText("Manage Supplier");

        ManageInverntory.setFont(new java.awt.Font("Forte", 1, 12)); // NOI18N
        ManageInverntory.setText("Manage Inventory");

        newSupplier.setFont(new java.awt.Font("Forte", 1, 12));
        newSupplier.setText("NEw Supplier");
        newSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSupplierActionPerformed(evt);
            }
        });

        updateSupplier.setFont(new java.awt.Font("Forte", 1, 12));
        updateSupplier.setText("Update Supplier");
        updateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSupplierActionPerformed(evt);
            }
        });

        searchSupplier.setFont(new java.awt.Font("Forte", 1, 12));
        searchSupplier.setText("search Supplier");
        searchSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSupplierActionPerformed(evt);
            }
        });

        newStock.setFont(new java.awt.Font("Forte", 1, 12)); // NOI18N
        newStock.setText("New Stock");
        newStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStockActionPerformed(evt);
            }
        });

        updateStock.setFont(new java.awt.Font("Forte", 1, 12));
        updateStock.setText("Update Stock");
        updateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStockActionPerformed(evt);
            }
        });

        searchStock.setFont(new java.awt.Font("Forte", 1, 12));
        searchStock.setText("Search Stock");
        searchStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStockActionPerformed(evt);
            }
        });

        LoginName.setEditable(false);
        LoginName.setFont(new java.awt.Font("Forte", 1, 12));
        LoginName.setText(" Hi !");
        LoginName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginNameActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Forte", 1, 12));
        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        AddProduct.setText("Add Product");
        AddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Forte", 1, 12));
        jButton3.setText("Add Employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ManageOrder2.setFont(new java.awt.Font("Forte", 1, 12));
        ManageOrder2.setText("Manage prmotion");

        ManageOrder3.setFont(new java.awt.Font("Forte", 1, 12));
        ManageOrder3.setText("Manage Sale");

        newSale.setFont(new java.awt.Font("Forte", 1, 12));
        newSale.setText("NEw Sale");
        newSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSaleActionPerformed(evt);
            }
        });

        searchSale.setFont(new java.awt.Font("Forte", 1, 12)); // NOI18N
        searchSale.setText("Search Sale");
        searchSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSaleActionPerformed(evt);
            }
        });

        AddPromotion.setFont(new java.awt.Font("Forte", 1, 12));
        AddPromotion.setText("Add Prmotion");
        AddPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPromotionActionPerformed(evt);
            }
        });

        veiwPromotion.setFont(new java.awt.Font("Forte", 1, 12));
        veiwPromotion.setText("Veiw Promotion");
        veiwPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiwPromotionActionPerformed(evt);
            }
        });

        ManageOrder1.setFont(new java.awt.Font("Forte", 1, 12));
        ManageOrder1.setText("Manage Promotion");

        ManageOrder4.setFont(new java.awt.Font("Forte", 1, 12));
        ManageOrder4.setText("Manage Employee");

        searchSale1.setFont(new java.awt.Font("Forte", 1, 12)); // NOI18N
        searchSale1.setText("Replace Sale");
        searchSale1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSale1ActionPerformed(evt);
            }
        });

        jMenu1.setMnemonic('F');
        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setMnemonic('E');
        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('E');
        jMenu2.setText("Edit");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setMnemonic('A');
        jMenuItem2.setText("About");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(ManageProduct))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(ManageSupplier))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(searchSupplier, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addComponent(newSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(newStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(ManageInverntory))
                                .addComponent(updateStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(updateProduct, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addComponent(SearchProduct, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addComponent(OrderStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(CancelOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(NewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(PlaceOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ManageOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AddProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(22, 22, 22)
                                                    .addComponent(ManageOrder3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(newSale, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                                .addComponent(searchSale, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                                .addComponent(veiwPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                                .addComponent(AddPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(ManageOrder4))
                                                .addComponent(searchSale1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                                        .addGap(837, 837, 837))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(348, 348, 348)
                                .addComponent(logout)
                                .addGap(61, 61, 61)
                                .addComponent(LoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(ManageOrder1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ManageOrder2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ManageOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaceOrder)
                    .addComponent(ManageOrder2)
                    .addComponent(ManageOrder1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CancelOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OrderStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddPromotion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veiwPromotion)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ManageProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewProduct)
                        .addGap(11, 11, 11)
                        .addComponent(SearchProduct)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateProduct)
                            .addComponent(searchSale1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ManageSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ManageOrder3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newSale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchSale)
                        .addGap(44, 44, 44)
                        .addComponent(ManageOrder4)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSupplier)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageInverntory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchStock)
                .addGap(261, 261, 261)
                .addComponent(AddProduct)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-588)/2, (screenSize.height-654)/2, 588, 654);
    }// </editor-fold>//GEN-END:initComponents

    private void PlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceOrderActionPerformed
      new PlaceOrder().setVisible(true);
}//GEN-LAST:event_PlaceOrderActionPerformed

    private void CancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelOrderActionPerformed
      new cancelOrder().setVisible(true);
}//GEN-LAST:event_CancelOrderActionPerformed

    private void OrderStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderStatusActionPerformed
      new orderStatus().setVisible(true);
}//GEN-LAST:event_OrderStatusActionPerformed

    private void NewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProductActionPerformed
           new valueMArt.newProduct().setVisible(true);
}//GEN-LAST:event_NewProductActionPerformed

    private void SearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchProductActionPerformed

            new SearchProduct().setVisible(true);
}//GEN-LAST:event_SearchProductActionPerformed

    private void updateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductActionPerformed
        new UpdateProduct().setVisible(true);
}//GEN-LAST:event_updateProductActionPerformed

    private void newSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSupplierActionPerformed
       new NewSupplier().setVisible(true);
}//GEN-LAST:event_newSupplierActionPerformed

    private void updateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSupplierActionPerformed
        new updateSupplier().setVisible(true);
}//GEN-LAST:event_updateSupplierActionPerformed

    private void searchSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSupplierActionPerformed
        new searchSupplier().setVisible(true);
}//GEN-LAST:event_searchSupplierActionPerformed

    private void newStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStockActionPerformed
        new NewStock().setVisible(true);
}//GEN-LAST:event_newStockActionPerformed

    private void updateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStockActionPerformed
        new updateStock().setVisible(true);
}//GEN-LAST:event_updateStockActionPerformed

    private void searchStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStockActionPerformed
       new searchStock().setVisible(true);
}//GEN-LAST:event_searchStockActionPerformed

    private void LoginNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginNameActionPerformed

}//GEN-LAST:event_LoginNameActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        JOptionPane.showMessageDialog(this, "Succesfully Logout !");

}//GEN-LAST:event_logoutActionPerformed

    private void AddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductActionPerformed
       
}//GEN-LAST:event_AddProductActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       new valueMArt.AddEmployee().setVisible(true);
}//GEN-LAST:event_jButton3ActionPerformed

private void newSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSaleActionPerformed
       new valueMArt.newSale().setVisible(true);
}//GEN-LAST:event_newSaleActionPerformed

private void searchSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSaleActionPerformed
     new valueMArt.searchSale().setVisible(true);
}//GEN-LAST:event_searchSaleActionPerformed

private void AddPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPromotionActionPerformed
        new valueMArt.addPromotion().setVisible(true);    
}//GEN-LAST:event_AddPromotionActionPerformed

private void veiwPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiwPromotionActionPerformed
        new valueMArt.veiwPromotion().setVisible(true);
}//GEN-LAST:event_veiwPromotionActionPerformed

private void searchSale1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSale1ActionPerformed
        new valueMArt.replacement().setVisible(true);
}//GEN-LAST:event_searchSale1ActionPerformed

public void  setEType(String EType){
        this.EType=EType;
    }
/**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
    private String EType;    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProduct;
    private javax.swing.JButton AddPromotion;
    private javax.swing.JButton CancelOrder;
    private javax.swing.JTextField LoginName;
    private javax.swing.JLabel ManageInverntory;
    private javax.swing.JLabel ManageOrder;
    private javax.swing.JLabel ManageOrder1;
    private javax.swing.JLabel ManageOrder2;
    private javax.swing.JLabel ManageOrder3;
    private javax.swing.JLabel ManageOrder4;
    private javax.swing.JLabel ManageProduct;
    private javax.swing.JLabel ManageSupplier;
    private javax.swing.JButton NewProduct;
    private javax.swing.JButton OrderStatus;
    private javax.swing.JButton PlaceOrder;
    private javax.swing.JButton SearchProduct;
    private javax.swing.JButton jButton3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton logout;
    private javax.swing.JButton newSale;
    private javax.swing.JButton newStock;
    private javax.swing.JButton newSupplier;
    private javax.swing.JButton searchSale;
    private javax.swing.JButton searchSale1;
    private javax.swing.JButton searchStock;
    private javax.swing.JButton searchSupplier;
    private javax.swing.JButton updateProduct;
    private javax.swing.JButton updateStock;
    private javax.swing.JButton updateSupplier;
    private javax.swing.JButton veiwPromotion;
    // End of variables declaration//GEN-END:variables

}
