/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newProduct.java
 *
 * Created on Jan 12, 2012, 1:17:31 AM
 */
package valueMArt;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Fhad khan
 */
public class newProduct extends javax.swing.JFrame {

    /** Creates new form newProduct */
    public newProduct() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/valuemart";
        String user = "root";
        String password = "";

        cb_Family.removeAllItems();
        cb_productName.removeAllItems();
        try {
            connection = (Connection) DriverManager.getConnection(url, user, password);
            statement = (Statement) connection.createStatement();
            resultset=statement.executeQuery("Select  Fname from family ");
            while (resultset.next()) {
                String cname=resultset.getString(1);
              cb_Family.addItem(cname);
            }
         } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
        check = true;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageOrder1 = new javax.swing.JLabel();
        cb_Family = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_Catagery = new javax.swing.JComboBox();
        addCatagery = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        catalogId = new javax.swing.JTextField();
        productId = new javax.swing.JTextField();
        cb_brand = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Manufacture = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cb_productName = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        varity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        size = new javax.swing.JTextField();
        Save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ManageOrder1.setFont(new java.awt.Font("Forte", 1, 12)); // NOI18N
        ManageOrder1.setText("              NEw Product");

        cb_Family.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_FamilyActionPerformed(evt);
            }
        });

        jLabel1.setText("Family");

        jLabel5.setText("Catagory");

        cb_Catagery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CatageryActionPerformed(evt);
            }
        });

        addCatagery.setFont(new java.awt.Font("Forte", 1, 12)); // NOI18N
        addCatagery.setText("Add Catagory");
        addCatagery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCatageryActionPerformed(evt);
            }
        });

        jLabel6.setText("Catalog ID");

        catalogId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogIdActionPerformed(evt);
            }
        });

        cb_brand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nike", "slaenger" }));
        cb_brand.setAutoscrolls(true);
        cb_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_brandActionPerformed(evt);
            }
        });

        jLabel8.setText("Brand");

        jLabel7.setText("Product ID");

        jLabel9.setText("Manufacture");

        jLabel11.setText("Product Name");

        cb_productName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_productNameActionPerformed(evt);
            }
        });

        jLabel12.setText("Varity");

        jLabel3.setText("Description");

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        jLabel10.setText("Product Size");

        Save.setFont(new java.awt.Font("Forte", 1, 12)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(ManageOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(addCatagery))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb_Family, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(cb_Catagery, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(varity, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(catalogId, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Manufacture, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(14, 14, 14)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(productId, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                            .addComponent(cb_productName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(cb_brand, 0, 110, Short.MAX_VALUE))
                                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(Save)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ManageOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_Family, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cb_Catagery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(addCatagery)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(catalogId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(productId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(varity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(cb_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(Manufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cb_productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(46, 46, 46)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cb_FamilyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_FamilyActionPerformed
        if(check == true) {
    cb_Catagery.removeAllItems();
    try {
            resultset = statement.executeQuery("SELECT FID FROM family WHERE Fname='" + cb_Family.getSelectedItem().toString() + "'");
            resultset.next();
            //System.out.println(resultset.getString(1));
            resultset=statement.executeQuery("Select  Name from Catagery WHERE FID='" + resultset.getString(1) + "'");
            while (resultset.next()) {
               String cname=resultset.getString(1);
              cb_Catagery.addItem(cname);                
            }
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }
}//GEN-LAST:event_cb_FamilyActionPerformed

private void cb_CatageryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CatageryActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cb_CatageryActionPerformed

private void catalogIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogIdActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_catalogIdActionPerformed

private void cb_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_brandActionPerformed
        String item=cb_brand.getSelectedItem().toString();
                cb_productName.removeAllItems();
        if(item.equals("nike")) {
            String qry="SELECT * from nike ";
            int i=0;
            try {
                resultset=statement.executeQuery(qry);
                while (resultset.next()) {
                    String name=resultset.getString(2);
                    cb_productName.addItem(name);                }
            } catch (Exception ex) {
                ex.getMessage();
            }
            
                    
        }else if(item.equals("slaenger")){
            cb_productName.removeAllItems();
            String qry="SELECT * from slanenger ";
            try {
                resultset=statement.executeQuery(qry);
                while (resultset.next()) {
                    String name=resultset.getString(1);
                    cb_productName.addItem(name);                }
            } catch (Exception ex) {
                ex.getMessage();
            }

        }
}//GEN-LAST:event_cb_brandActionPerformed

private void cb_productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_productNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cb_productNameActionPerformed

private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        String Id=productId.getText();
        String CID=catalogId.getText();
        String brnd=cb_brand.getSelectedItem().toString();
        String siz=size.getText();
        String manf=Manufacture.getText();
        String var=varity.getText();
        String des=description.getText();
        String pName=cb_productName.getSelectedItem().toString();


        String url = "jdbc:mysql://localhost:3306/valuemart";
        String user = "root";
        String password = "";

        try {
            connection = DriverManager.getConnection(url, user, password);
            statement = (Statement) connection.createStatement();
         statement.executeUpdate("INSERT INTO product(CatalogID,ProductID,ProductName,ProductBrand,ProductSize,Manufacture,variety,ProductDescription) VALUES('" + CID + "','" + Id + "','" + pName + "','" + brnd + "','" + siz + "','" + manf + "','" + var + "','" + des + "')");
       
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        } finally {
            try {
                if (resultset != null) {
                    resultset.close();
                }
                if (connection != null) {
                    connection.close();
                }

            } catch (Exception ex) {
                System.err.println("Finally: " + ex.getMessage());
            }
        }

                 
}//GEN-LAST:event_SaveActionPerformed

private void addCatageryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCatageryActionPerformed
    new addCatagory().setVisible(true); 
}//GEN-LAST:event_addCatageryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new newProduct().setVisible(true);
            }
        });
    }
    
    private Connection connection;
    private Statement statement;
    private ResultSet resultset;
    private boolean check=false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ManageOrder1;
    private javax.swing.JTextField Manufacture;
    private javax.swing.JButton Save;
    private javax.swing.JButton addCatagery;
    private javax.swing.JTextField catalogId;
    private javax.swing.JComboBox cb_Catagery;
    private javax.swing.JComboBox cb_Family;
    private javax.swing.JComboBox cb_brand;
    private javax.swing.JComboBox cb_productName;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField productId;
    private javax.swing.JTextField size;
    private javax.swing.JTextField varity;
    // End of variables declaration//GEN-END:variables
}
