/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * veiwPromotion.java
 *
 * Created on Jan 8, 2012, 4:14:59 AM
 */
package valueMArt;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fhad khan
 */
public class veiwPromotion extends javax.swing.JFrame {

    /** Creates new form veiwPromotion */
    public veiwPromotion() {
        String url = "jdbc:mysql://localhost:3306/valuemart";
        String user = "root";
        String password = "";

        try {
            connection = DriverManager.getConnection(url, user, password);
            statement = connection.createStatement();


        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }

        model=new javax.swing.table.DefaultTableModel(
                    new Object[][]{},new String[]{
                "Promotion ID","Promotion Name","Promotion Type","Catagery","Discount","Start Date","Ending Date"

            }){
                Class [] type=new Class[]{
                    java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class
                };
                boolean[] canEdit =new boolean []{
                    false,false,false,false,false,false,false
                };
                
                public Class getColmnClass(int columnIndex){
                    return type[columnIndex];

                }
            @Override
                public boolean isCellEditable(int rowindex,int columnIndex){
                    return canEdit[columnIndex];
                }
            };

        initComponents();
        tb_promotion=new JTable(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        promotionField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_promotion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Veiw Promotion");
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Forte", 1, 12));
        jLabel3.setText("Prmton Id");

        promotionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promotionFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Forte", 1, 14)); // NOI18N
        jLabel4.setText("Veiw Promtoin");

        Search.setFont(new java.awt.Font("Forte", 1, 12));
        Search.setText("Look Up");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        tb_promotion.setModel(model);
        jScrollPane1.setViewportView(tb_promotion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(promotionField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(234, 234, 234))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promotionField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void promotionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promotionFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_promotionFieldActionPerformed

private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        String ID=promotionField.getText();
        if(count ==0){    
                String qry=("Select * FROM promotion where PID='"+ID+"'");
                try {
                    resultset = statement.executeQuery(qry);
                    while(resultset.next()){
                        String PID=resultset.getString(1);
                        String PName=resultset.getString(2);
                        String Ptype=resultset.getString(3);
                        String Catagery=resultset.getString(4);
                        String Discount=resultset.getString(5);
                        String SDate=resultset.getString(6);
                        String EDate=resultset.getString(7);
                        model.addRow(new Object[]{PID,PName,Ptype,Catagery,Discount,SDate,EDate});
                        count++;
                    }

                } catch (Exception ex) {
                   ex.getMessage();
                }
         
        }else if(count!=0){
                int row=model.getRowCount()-1;
                String pid=(model.getValueAt(row,0)).toString();
                if(pid.equals(ID)){
                    JOptionPane.showMessageDialog(this,"Record AllReady printed");
                        }else{
                            String qry=("Select * FROM promotion where PID='"+ID+"'");
                        try {
                            resultset = statement.executeQuery(qry);
                            while(resultset.next()){
                                String PID=resultset.getString(1);
                                String PName=resultset.getString(2);
                                String Ptype=resultset.getString(3);
                                String Catagery=resultset.getString(4);
                                String Discount=resultset.getString(5);
                                String SDate=resultset.getString(6);
                                String EDate=resultset.getString(7);
                                model.addRow(new Object[]{PID,PName,Ptype,Catagery,Discount,SDate,EDate});
                            }

                        } catch (Exception ex) {
                           ex.getMessage();
                        }
                    
                   }
            }
        
}//GEN-LAST:event_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(veiwPromotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(veiwPromotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(veiwPromotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(veiwPromotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new veiwPromotion().setVisible(true);
            }
        });
    }
    private static int count=0;
    private DefaultTableModel model;
    private Connection connection;
    private Statement statement;
    private ResultSet resultset;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField promotionField;
    private javax.swing.JTable tb_promotion;
    // End of variables declaration//GEN-END:variables
}
